### ISSUE TITLE
Código de retorno possivelmente incompletos?

### ISSUE THREAD

**Issue by LeafarDev** [tarcisioruas/shopfacil-bradesco-registro-boleto#2]
Os códigos 93005119 ("REGISTRO EFETUADO COM SUCESSO - CIP CONFIRMADA") e  93005999("BOLETO GERADO COM SUCESSO - REGISTRO EM PROCESSAMENTO") não deveriam estar na lista de registrados ?

**Comment by tarcisioruas** [comment]
Olá @LeafarDev. Vou checar a documentação e incluir os mesmos. Você também pode fazer se quiser e enviar um Pull request, ai você fica na lista de contribuidores.

Obrigado pela ajuda.

**Comment by tarcisioruas** [comment]
> Os códigos 93005119 ("REGISTRO EFETUADO COM SUCESSO - CIP CONFIRMADA") e 93005999("BOLETO GERADO COM SUCESSO - REGISTRO EM PROCESSAMENTO") não deveriam estar na lista de registrados ?

Olá @LeafarDev. Vou checar a documentação e incluir os mesmos. Você também pode fazer se quiser e enviar um Pull request, ai você fica na lista de contribuidores.

Obrigado pela ajuda.

**Comment by tarcisioruas** [comment]
Problema corrigido na versão 1.3
Obrigado pela ajuda @LeafarDev
