### ISSUE TITLE
Ajuda com configuração

### ISSUE THREAD

**Issue by gustavosfreitas** [tarcisioruas/shopfacil-bradesco-registro-boleto#3]
Olá. 

Estou fazendo a configuração pela primeira vez utilizando Laravel 5.6. Ao chamar o controller estou recebendo o seguinte retorno:

ShopFacil\Registro\Exceptions\HttpException' with message 'Erro ao efetuar requisição: SSL certificate problem: unable to get local issuer certificate

Alguém sabe como devo configurar isso ?

Grato.

**Comment by tarcisioruas** [comment]
Olá @gustavosfreitas. Estou verificando nesse momento, assim que eu tiver uma resposta vou responder.

**Comment by gustavosfreitas** [comment]
Obrigado Tarcisio.

Eu já tempo os certificados PFX e PEM.

**Comment by tarcisioruas** [comment]
Aparentemente é um problema de configuração do ambiente e não da lib
propriamente dita. Qual seu Sistema Operacional e a versão do PHP?

Em qui, 22 de ago de 2019 às 20:39, gustavosfreitas <
notifications@github.com> escreveu:

**Comment by gustavosfreitas** [comment]
Estou com um ambiente de teste na minha estação - Windows com PHP 5.6

**Comment by tarcisioruas** [comment]
Está usando Wamp, Xampp ou montou fez a instalação de forma manual?

Em qui, 22 de ago de 2019 às 21:29, gustavosfreitas <
notifications@github.com> escreveu:

**Comment by gustavosfreitas** [comment]
Aqui estou usando XAMPP

**Comment by gustavosfreitas** [comment]
Tentei mudar o curl.cainfo="C:\xampp\php\snr_public.pem" no php.ini, mas também não foi

**Comment by tarcisioruas** [comment]
Esse arquivo que você está referenciando no curl.cainfo existe?

**Comment by gustavosfreitas** [comment]
Sim. Baixei um cacert que viu em outro forum e tentei:

curl.cainfo="C:\xampp\php\cacert.pem"

Mesma coisa...

**Comment by ricardotorquato** [comment]
Olá @gustavosfreitas... você já verificou se o seu PHP ta conseguindo ler arquivos nesse diretório corretamente? Tentou fazer um `file_exists` por exemplo?

**Comment by tarcisioruas** [comment]
Como está iniciando o Laravel? php artisan serve?

**Comment by gustavosfreitas** [comment]
> Como está iniciando o Laravel? php artisan serve?

Não. A aplicação já roda direto no server (neste caso no Xampp)

**Comment by tarcisioruas** [comment]
A solução mais encontrada na internet para esse problema é realmente fazer o download do certificado no link http://curl.haxx.se/ca/cacert.pem e salvá-lo num diretório, tipo C:\certificados,
ai o path ficaria "C:\certificados\cacert.pem" e depois fazer o apontamento para o arquivo dentro do php.ini.

`
curl.cainfo = "C:\certificados\cacert.pem"
`
Isso tem funcionado para várias pessoas na Internet

**Comment by tarcisioruas** [comment]
> > Como está iniciando o Laravel? php artisan serve?
> 
> Não. A aplicação já roda direto no server (neste caso no Xampp)

Eu sei que você está fazendo, mas eu vou perguntar mesmo assim. Você está reiniciando o Apache toda vez que edita o php.ini?

**Comment by gustavosfreitas** [comment]
É justamente o que tenho feito....mas continuo tomando este erro:

[2019-08-22 22:02:35] local.ERROR: exception 'ShopFacil\Registro\Exceptions\HttpException' with message 'Erro ao efetuar requisição: SSL certificate problem: unable to get local issuer certificate' in C:\xampp\htdocs\smart_admin\local\vendor\tarcisioruas\bradesco-registro-online\src\Registro\Http.php:27

**Comment by gustavosfreitas** [comment]
> > > Como está iniciando o Laravel? php artisan serve?
> > 
> > 
> > Não. A aplicação já roda direto no server (neste caso no Xampp)
> 
> Eu sei que você está fazendo, mas eu vou perguntar mesmo assim. Você está reiniciando o Apache toda vez que edita o php.ini?

Sim...

**Comment by gustavosfreitas** [comment]
Achei um post falando para usar essa chamada curl_setopt($canal, CURLOPT_SSL_VERIFYPEER, false); para não fazer a verificação ssl.

Aí o erro já deu do webservice:

<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:registrarTituloResponse xmlns:ns2="http://ws.registrotitulo.ibpj.web.bradesco.com.br/"><return>{"cdErro":"810", "msgErro":"Erro Certificado / Formatacao dos campos da mensagem invalida [0x00d30003]"}</return></ns2:registrarTituloResponse></S:Body></S:Envelope>

**Comment by tarcisioruas** [comment]
As ultimas coisas que consigo pensar são:

Verifica que você está editando o php.ini certo. Se você colocar um arquivo com o código abaixo na pasta C:\xampp\htdocs\ e abrir o mesmo no navegador, vai saber exatamente qual o php.ini que o sistema está usando.
```php
<?php
phpinfo();
?>
```
![Captura de Tela 2019-08-22 às 22 17 37](https://user-images.githubusercontent.com/1655864/63560029-bc4d6d80-c52a-11e9-8c88-da94e590451c.png)

Se confirmar que tudo está correto, vá até onde está localizado o arquivo de permissão, clica com o botão direito do mouse no mesmo, depois clique em Propriedades e verifica se ele não está bloqueado.

![desbloquear-um-arquivo-marcado-como-nao-confiavel-no-windows-10-1](https://user-images.githubusercontent.com/1655864/63560146-4695d180-c52b-11e9-9801-28213bc42335.png)

![desbloquear-um-arquivo-marcado-como-nao-confiavel-no-windows-10-2](https://user-images.githubusercontent.com/1655864/63560567-e43dd080-c52c-11e9-8a7a-b021df5b303c.png)

Se nada disso der certo. 

Sei que não se pode editar arquivos na pasta vendor e sei que o problema está acontecendo porque a url do banco usa https e a lib de boletos usa curl. O Curl usa o certificado local para fazer a requisição, mas você pode editar essa checagem.

Para isso acesse o arquivo vendor/tarcisioruas/bradesco-registro-online/src/Registro/Http.php
e adiciona o código abaixo depois da linha 18 e antes do código da linha 20.

`
curl_setopt($canal, CURLOPT_SSL_VERIFYPEER, false);
`
Ficando assim

```php
curl_setopt($canal, CURLOPT_RETURNTRANSFER, true);
curl_setopt($canal, CURLOPT_SSL_VERIFYPEER, false);
$resposta = curl_exec($canal);
```

Lembrando que por segurança, isso não deve ser feito na produção.

**Comment by tarcisioruas** [comment]
> Achei um post falando para usar essa chamada curl_setopt($canal, CURLOPT_SSL_VERIFYPEER, false); para não fazer a verificação ssl.
> 
> Aí o erro já deu do webservice:
> 
> <S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenv="[http://schemas.xmlsoap.org/soap/envelope/">](http://schemas.xmlsoap.org/soap/envelope/%22%3E)<S:Body><ns2:registrarTituloResponse xmlns:ns2="[http://ws.registrotitulo.ibpj.web.bradesco.com.br/">](http://ws.registrotitulo.ibpj.web.bradesco.com.br/%22%3E){"cdErro":"810", "msgErro":"Erro Certificado / Formatacao dos campos da mensagem invalida [0x00d30003]"}</ns2:registrarTituloResponse></S:Body></S:Envelope>

Mal sinal, significa que desativar a checagem do certificado não vai dar certo nesse caso.

Você está conectando no ambiente de testes do Bradesco ou já está tentando usar a produção direto?

**Comment by gustavosfreitas** [comment]
Ambiente de testes...

Passei a forçar o local no próprio código:

        curl_setopt($canal, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($canal, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($canal, CURLOPT_CAINFO, 'C:\xampp\php\snr_public.pem');

Mas dá o retorno do Bradesco com o erro 801.

**Comment by gustavosfreitas** [comment]
Mais uma vez obrigado pelas respostas....

**Comment by tarcisioruas** [comment]
> Ambiente de testes...
> 
> Passei a forçar o local no próprio código:
> 
> ```
>     curl_setopt($canal, CURLOPT_SSL_VERIFYPEER, 0);
>     curl_setopt($canal, CURLOPT_SSL_VERIFYHOST, 0);
>     curl_setopt($canal, CURLOPT_CAINFO, 'C:\xampp\php\snr_public.pem');
> ```
> 
> Mas dá o retorno do Bradesco com o erro 801.

Retorna um erro, mas não mostra mensagem nenhuma? Retorna só um código de erro?

No manual de integração que tenho, não encontrei esse código de retorno

**Comment by tarcisioruas** [comment]
Achei um link interessante sobre o certificado no windows

[https://github.com/laravelbrasil/forum/issues/111#issuecomment-312366292](https://github.com/laravelbrasil/forum/issues/111#issuecomment-312366292)

**Comment by gustavosfreitas** [comment]
Muito estranho... 

[2019-08-23 11:52:42] local.INFO: https://cobranca.bradesconetempresa.b.br/ibpjregistrotitulows/registrotitulohomologacao  
[2019-08-23 11:52:42] local.INFO: {"merchant_id":"seuMerchantIdAqui","boleto":{"carteira":26,"nosso_numero":1234,"numero_documento":1234,"data_emissao":"2019-08-23","data_vencimento":"2019-08-31","valor_titulo":"100","pagador":{"nome":"Gustavo Freitas","documento":"09110630724","tipo_documento":1,"endereco":{"cep":"20520055","logradouro":"Rua Conde de Bonfim","numero":"680","complemento":"apto 802","bairro":"Tijuca","cidade":"Rio de Janeiro","uf":"RJ"}},"informacoes_opcionais":{"controle_participante":1234,"especie":"DV","aceite":"N","tipo_emissao_papeleta":2,"perc_multa_atraso":200000,"valor_multa_atraso":2,"qtde_dias_multa_atraso":1,"perc_juros":10000,"valor_juros":0,"qtde_dias_juros":1,"perc_desconto_1":1000000,"valor_desconto_1":1000000,"data_limite_desconto_1":"2019-08-31"}}}  
[2019-08-23 11:52:42] local.INFO: array (
  0 => 'Authorization: Basic c2V1TWVyY2hhbnRJZEFxdWk6c3VhU2VuaGFBcXVp',
  1 => 'Accept: application/json',
  2 => 'Accept-Charset: UTF-8',
  3 => 'Content-Type: application/json;UTF-8',
)  
[2019-08-23 11:52:42] local.INFO: C:\xampp\php\extras\ssl\cacert.pem  
[2019-08-23 11:52:44] local.INFO:   
[2019-08-23 11:52:44] local.INFO: chegou aqui  
[2019-08-23 11:52:44] local.ERROR: exception 'ShopFacil\Registro\Exceptions\HttpException' with message 'Erro ao efetuar requisição: SSL certificate problem: unable to get local issuer certificate' in C:\xampp\htdocs\smart_admin\local\vendor\tarcisioruas\bradesco-registro-online\src\Registro\Http.php:44

Até coloquei para exibir da onde ele pegaria o certificado para não ter problema de estar pegando do lugar errado.

Mesmo assim... nada.

**Comment by tarcisioruas** [comment]
Uma coisa importante, vi que se você estiver setando o certificado na mão o CURLOPT_SSL_VERIFYPEER tem que ser 1 ou true conforme abaixo.

```php
curl_setopt($canal, CURLOPT_SSL_VERIFYPEER, 1);
curl_setopt($canal, CURLOPT_CAINFO, 'C:\xampp\php\snr_public.pem');
```

**Comment by gustavosfreitas** [comment]
Mesma coisa.... que loucura....

**Comment by gustavosfreitas** [comment]
O seu código está fazendo isso:

Assinatura de Mensagens:
Com proposito de consistir a autenticidade e integridade, ou seja, garantir que
as informações do boleto são verdadeiras e não foram alteradas, toda
mensagem de registro de títulos será assinada digitalmente utilizando o
padrão PKCS#7 com os algoritmos RSA 2048 e SHA256
(sha256WithRSAEncryption), conforme layout das mensagens de entrada
definidas neste manual. Para isso, é necessário conhecer a cadeia de
certificados das autoridades certificadoras do responsável pela assinatura da
mensagem. 

Obrigado.

**Comment by tarcisioruas** [comment]
> O seu código está fazendo isso:
> 
> Assinatura de Mensagens:
> Com proposito de consistir a autenticidade e integridade, ou seja, garantir que
> as informações do boleto são verdadeiras e não foram alteradas, toda
> mensagem de registro de títulos será assinada digitalmente utilizando o
> padrão PKCS#7 com os algoritmos RSA 2048 e SHA256
> (sha256WithRSAEncryption), conforme layout das mensagens de entrada
> definidas neste manual. Para isso, é necessário conhecer a cadeia de
> certificados das autoridades certificadoras do responsável pela assinatura da
> mensagem.
> 
> Obrigado.

A lib não está fazendo a encriptação de maneira direta. Isso fica por conta do transporte por baixo dos panos. Quero dizer que isso fica por conta do certificado ssl do servidor do banco e biblioteca curl do sistema. Não há nada no código PHP dessa lib que faça isso propriamente dito.

**Comment by tarcisioruas** [comment]
Vou fazer uma modificação mais tarde para usar mais Curl. Talvez assim tiramos essa dependência que está causando problemas.

**Comment by gustavosfreitas** [comment]
Vamos ver conseguirei fazer funcionar... enquanto isso estou pesquisando e tentando aqui.

**Comment by gustavosfreitas** [comment]
Inclusive já instalei outro XAMPP com o PHP versão 7 para ver se tinha alguma coisa. Mas continua o mesmo erro "Erro ao efetuar requisição: SSL certificate problem: unable to get local issuer certificate"

**Comment by tarcisioruas** [comment]
Fiz algumas modificações para dar a opção de não usar mais o cURL e sim o PHP Stream Wrappers. Talvez funcione para você.

Para fazer o teste, precisa ativar a opção allow_url_fopen no php.ini do ambiente.

Ai basta substituir a linha

```php
// Por padrão, o cURL será usado. 
$registro = new Registro($ambiente, $merchantId, $senha);
```
por
```php
/* 
* Se desejar usar com PHP Stream Wrapper, use como abaixo
*/ 
$registro = new Registro($ambiente, $merchantId, $senha, new ShopFacil\Registro\StreamHttp());
```

**Comment by tarcisioruas** [comment]
O problema se dá por uma configuração no certificado do servidor / host e não propriamente um erro de código.

**Comment by gustavosfreitas** [comment]
Obrigado pelo retorno.

[image: logo_sonnar]

*Gustavo Freitas*
SONNAR | Soluções em Tecnologia

E-mail: gustavo@sonnartecnologia.com.br
Telefone: (21) 3563-4825
www.sonnartecnologia.com.br


    Você já conhece o *Smartcash* ?
    Uma solução *ágil*, *fácil* e *segura* para fazer a gestão financeira
do seu negócio. Conheça mais em *www.smartcash.com.br
<http://www.smartcash.com.br>*.


    *Atenção:* Essa mensagem (incluindo qualquer anexo) é destinada
exclusivamente ao seu destinatário e pode conter informações confidenciais,
protegidas por sigilo profissional ou cuja divulgação seja proibida por
lei. Se a mensagem foi recebida por engano, por favor, avise o remetente e
apague-a do computador. O uso não autorizado de tais informações é proibido
e está sujeito às penalidades cabíveis.

    *Notice of Confidentiality:* This message (including any attachments)
is intended exclusively for its addressee and may contain information that
is confidential and protected by a professional privilege or whose
disclosure is prohibited by law. If this message has been received in
error, please notify the sender and delete it immediately. Unauthorized use
of such information is prohibited and subject to applicable penalties.



Em qua., 17 de fev. de 2021 às 09:01, tarcisioruas <notifications@github.com>
escreveu:

**Comment by tarcisioruas** [comment]
@gustavosfreitas Você ainda usa essa lib? Está funcionando adequadamente?
