### ISSUE TITLE
Do nada o código começou a retornar erro 502

### ISSUE THREAD

**Issue by matheuscoelho** [tarcisioruas/shopfacil-bradesco-registro-boleto#5]
Estou usando Curl, comentei as linhas do curl no CurlHttp.php e o erro 502 sumiu, mas n consegui arrumar o código, alguém pode me ajudar?
O estranho é que funcionou por vários meses e do nada parou.
Estou usando o curl assim.

        $canal = curl_init();
        curl_setopt($canal, CURLOPT_URL, $url);
        curl_setopt($canal, CURLOPT_POST, 1);
        curl_setopt($canal, CURLOPT_POSTFIELDS, $dados);
        curl_setopt($canal, CURLOPT_HTTPHEADER, $cabecalhos);
        curl_setopt($canal, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($canal, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($canal, CURLOPT_SSL_VERIFYPEER, 0);

**Comment by tarcisioruas** [comment]
Olá @matheuscoelho, tenho um código que está atualmente em produção e é usado centenas de vezes por dia. Ele está configurado um pouco diferente do seu. Veja se as diferenças te ajudam.


```php
$canal = curl_init();
curl_setopt($canal, CURLOPT_URL, $url );
curl_setopt($canal, CURLOPT_POST, 1 );
curl_setopt($canal, CURLOPT_POSTFIELDS, $dados);
curl_setopt($canal, CURLOPT_HTTPHEADER, $cabecalhos);
curl_setopt($canal, CURLOPT_RETURNTRANSFER, true);
curl_setopt($canal, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_1);
```

É interessante verificar se houve altuma atualização / alteração no servidor onde o código está rodando. Tipo alguma atualização de bibliotecas de assinatura, tls ou coisas do tipo.

**Comment by matheuscoelho** [comment]
não funcionou, o houveram mudanças no serv, foi do nada mesmo. Mas obg por tentar ajudar, vou tentar reinstalar o linux, php.. tudo de novo
